name: docker-artilleriet

on:
  push:
    branches: "latest"
  pull_request:
    branches: "latest"

  workflow_dispatch:

jobs:
  docker:
    runs-on: debian-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: next
          push: true
          tags: dacdevops/artilleriet:latest
          file: Dockerfile